In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Dataset.csv')
pd.set_option('display.max_columns', None)
df.columns = df.columns.str.lower()
df.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,onlinebackup,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [3]:
for idx, row in df.iterrows():
    if df.loc[idx,'phoneservice'] == 'No':
        df.loc[idx,'multiplelines'] = 'No'
    if df.loc[idx,'internetservice'] == 'No':
        df.loc[idx,['onlinesecurity','onlinebackup','deviceprotection','techsupport','streamingtv','streamingmovies']] = 'No'

In [4]:
# Iterating through all the columns to understand the contents of the data
for each in df.columns:
    print(f"Number of {each}: {df[each].nunique()}")
    print(f"Options of {each}: {df[each].unique()}")
    print(f"Value counts: {df[each].value_counts()}")
    print()

Number of customerid: 7043
Options of customerid: ['7590-VHVEG' '5575-GNVDE' '3668-QPYBK' ... '4801-JZAZL' '8361-LTMKD'
 '3186-AJIEK']
Value counts: 7590-VHVEG    1
3791-LGQCY    1
6008-NAIXK    1
5956-YHHRX    1
5365-LLFYV    1
             ..
9796-MVYXX    1
2637-FKFSY    1
1552-AAGRX    1
4304-TSPVK    1
3186-AJIEK    1
Name: customerid, Length: 7043, dtype: int64

Number of gender: 2
Options of gender: ['Female' 'Male']
Value counts: Male      3555
Female    3488
Name: gender, dtype: int64

Number of seniorcitizen: 2
Options of seniorcitizen: [0 1]
Value counts: 0    5901
1    1142
Name: seniorcitizen, dtype: int64

Number of partner: 2
Options of partner: ['Yes' 'No']
Value counts: No     3641
Yes    3402
Name: partner, dtype: int64

Number of dependents: 2
Options of dependents: ['No' 'Yes']
Value counts: No     4933
Yes    2110
Name: dependents, dtype: int64

Number of tenure: 73
Options of tenure: [ 1 34  2 45  8 22 10 28 62 13 16 58 49 25 69 52 71 21 12 30 47 72 17 27
  5 46 11 70 63 43 15 60 18 66  9  3 31 50 64 56  7 42 35 48 29 65 38 68
 32 55 37 36 41  6  4 33 67 23 57 61 14 20 53 40 59 24 44 19 54 51 26  0
 39]
Value counts: 1     613
72    362
2     238
3     200
4     176
     ...
28     57
39     56
44     51
36     50
0      11
Name: tenure, Length: 73, dtype: int64

Number of phoneservice: 2
Options of phoneservice: ['No' 'Yes']
Value counts: Yes    6361
No      682
Name: phoneservice, dtype: int64

Number of multiplelines: 2
Options of multiplelines: ['No' 'Yes']
Value counts: No     4072
Yes    2971
Name: multiplelines, dtype: int64

Number of internetservice: 3
Options of internetservice: ['DSL' 'Fiber optic' 'No']
Value counts: Fiber optic    3096
DSL            2421
No             1526
Name: internetservice, dtype: int64

Number of onlinesecurity: 2
Options of onlinesecurity: ['No' 'Yes']
Value counts: No     5024
Yes    2019
Name: onlinesecurity, dtype: int64

Number of onlinebackup: 2
Options of onlinebackup: ['Yes' 'No']
Value counts: No     4614
Yes    2429
Name: onlinebackup, dtype: int64

Number of deviceprotection: 2
Options of deviceprotection: ['No' 'Yes']
Value counts: No     4621
Yes    2422
Name: deviceprotection, dtype: int64

Number of techsupport: 2
Options of techsupport: ['No' 'Yes']
Value counts: No     4999
Yes    2044
Name: techsupport, dtype: int64

Number of streamingtv: 2
Options of streamingtv: ['No' 'Yes']
Value counts: No     4336
Yes    2707
Name: streamingtv, dtype: int64

Number of streamingmovies: 2
Options of streamingmovies: ['No' 'Yes']
Value counts: No     4311
Yes    2732
Name: streamingmovies, dtype: int64

Number of contract: 3
Options of contract: ['Month-to-month' 'One year' 'Two year']
Value counts: Month-to-month    3875
Two year          1695
One year          1473
Name: contract, dtype: int64

Number of paperlessbilling: 2
Options of paperlessbilling: ['Yes' 'No']
Value counts: Yes    4171
No     2872
Name: paperlessbilling, dtype: int64

Number of paymentmethod: 4
Options of paymentmethod: ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
Value counts: Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: paymentmethod, dtype: int64

Number of monthlycharges: 1585
Options of monthlycharges: [29.85 56.95 53.85 ... 63.1  44.2  78.7 ]
Value counts: 20.05     61
19.85     45
19.95     44
19.90     44
20.00     43
          ..
23.65      1
114.70     1
43.65      1
87.80      1
78.70      1
Name: monthlycharges, Length: 1585, dtype: int64

Number of totalcharges: 6531
Options of totalcharges: ['29.85' '1889.5' '108.15' ... '346.45' '306.6' '6844.5']
Value counts:           11
20.2      11
19.75      9
20.05      8
19.9       8
          ..
6849.4     1
692.35     1
130.15     1
3211.9     1
6844.5     1
Name: totalcharges, Length: 6531, dtype: int64

Number of churn: 2
Options of churn: ['No' 'Yes']
Value counts: No     5174
Yes    1869
Name: churn, dtype: int64

In [5]:
df.totalcharges = pd.to_numeric(df.totalcharges, errors='coerce')

In [6]:
df["totalcharges"].fillna(0, inplace = True)

In [7]:
columns=[]
for i in df.columns:
    if len(df[i].unique()) <= 2:
        columns.append(i)
columns

['gender',
 'seniorcitizen',
 'partner',
 'dependents',
 'phoneservice',
 'multiplelines',
 'onlinesecurity',
 'onlinebackup',
 'deviceprotection',
 'techsupport',
 'streamingtv',
 'streamingmovies',
 'paperlessbilling',
 'churn']

In [8]:
dumdum=pd.get_dummies(df,columns=columns,drop_first=True)
dumdum = pd.get_dummies(dumdum, columns = ['internetservice','contract','paymentmethod'])
dumdum.rename(columns= {'seniorcitizen_1':'seniorcitizen_Yes'}, inplace= True)
dumdum.head(20)

,customerid,tenure,monthlycharges,totalcharges,gender_Male,seniorcitizen_Yes,partner_Yes,dependents_Yes,phoneservice_Yes,multiplelines_Yes,onlinesecurity_Yes,onlinebackup_Yes,deviceprotection_Yes,techsupport_Yes,streamingtv_Yes,streamingmovies_Yes,paperlessbilling_Yes,churn_Yes,internetservice_DSL,internetservice_Fiber optic,internetservice_No,contract_Month-to-month,contract_One year,contract_Two year,paymentmethod_Bank transfer (automatic),paymentmethod_Credit card (automatic),paymentmethod_Electronic check,paymentmethod_Mailed check
0,7590-VHVEG,1,29.85,29.85,0,0,1,0,0,0,0,1,0,0,0,0,1,0,1,0,0,1,0,0,0,0,1,0
1,5575-GNVDE,34,56.95,1889.50,1,0,0,0,1,0,1,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1
2,3668-QPYBK,2,53.85,108.15,1,0,0,0,1,0,1,1,0,0,0,0,1,1,1,0,0,1,0,0,0,0,0,1
3,7795-CFOCW,45,42.30,1840.75,1,0,0,0,0,0,1,0,1,1,0,0,0,0,1,0,0,0,1,0,1,0,0,0
4,9237-HQITU,2,70.70,151.65,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0,1,0,1,0,0,0,0,1,0
5,9305-CDSKC,8,99.65,820.50,0,0,0,0,1,1,0,0,1,0,1,1,1,1,0,1,0,1,0,0,0,0,1,0
6,1452-KIOVK,22,89.10,1949.40,1,0,0,1,1,1,0,1,0,0,1,0,1,0,0,1,0,1,0,0,0,1,0,0
7,6713-OKOMC,10,29.75,301.90,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1
8,7892-POOKP,28,104.80,3046.05,0,0,1,0,1,1,0,0,1,1,1,1,1,1,0,1,0,1,0,0,0,0,1,0
9,6388-TABGU,62,56.15,3487.95,1,0,0,1,1,0,1,1,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0
10,9763-GRSKD,13,49.95,587.45,1,0,1,1,1,0,1,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,1
11,7469-LKBCI,16,18.95,326.80,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,1,0,0
12,8091-TTVAX,58,100.35,5681.10,1,0,1,0,1,1,0,0,1,0,1,1,0,0,0,1,0,0,1,0,0,1,0,0
13,0280-XJGEX,49,103.70,5036.30,1,0,0,0,1,1,0,1,1,0,1,1,1,1,0,1,0,1,0,0,1,0,0,0
14,5129-JLPIS,25,105.50,2686.05,1,0,0,0,1,0,1,0,1,1,1,1,1,0,0,1,0,1,0,0,0,0,1,0
15,3655-SNQYZ,69,113.25,7895.15,0,0,1,1,1,1,1,1,1,1,1,1,0,0,0,1,0,0,0,1,0,1,0,0
16,8191-XWSZG,52,20.65,1022.95,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1
17,9959-WOFKT,71,106.70,7382.25,1,0,0,1,1,1,1,0,1,0,1,1,0,0,0,1,0,0,0,1,1,0,0,0
18,4190-MFLUW,10,55.20,528.35,0,0,1,1,1,0,0,0,1,1,0,0,0,1,1,0,0,1,0,0,0,1,0,0
19,4183-MYFRB,21,90.05,1862.90,0,0,0,0,1,0,0,1,1,0,0,1,1,0,0,1,0,1,0,0,0,0,1,0

In [9]:
dumdum.to_csv('Dummy_data.csv', index=False)